name: widget_tree_decomposer
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/adambossy/widget_tree_decomposer

environment:
  sdk: ^3.0.6

dependencies:
  analyzer: ^3.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
