name: widget_tree_decomposer
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/adambossy/widget_tree_decomposer

environment:
  sdk: ^3.0.6

dependencies:
  analyzer: ^6.1.0
  code_builder: ^4.5.0
  dart_style: ^2.3.2
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
